import {
  maria,
  zepex,
  fred,
  paixao,
  jacqueline,
  raphael,
  felipe,
  cesar,
  gustavo,
  bonafe,
  pepeLatao,
  boeckL,
  miele,
  zeze,
  zezeCoringa,
  mieleCoringa,
  pepeCoringa,
  khezacCoringa,
  boeckCoringa,
  miguelito,
  kaiky,
  yuyu,
  joao,
  mieleAmem,
  victor,
  turma,
} from "../../assets";

export const cards = [
  {
    title: "OODAMA Fred",
    price: "0.1 ETH",
    img: fred,
    raridade: "lendária",
  },
  {
    title: "Portugol 3",
    price: "0.1 ETH",
    img: raphael,
    raridade: "lendária",
  },
  {
    title: "Emanuel",
    price: "0.07 ETH",
    img: felipe,
    raridade: "lendária",
  },
  {
    title: "Te amamos Jacqueline",
    price: "0.1 ETH",
    img: jacqueline,
    raridade: "lendária",
  },
  {
    title: "Zepinhaaaa",
    price: "0.1 ETH",
    img: zepex,
    raridade: "lendária",
  },
  {
    title: "Paixão",
    price: "0.1 ETH",
    img: paixao,
    raridade: "lendária",
  },
  {
    title: "Maria Teresa",
    price: "0.1 ETH",
    img: maria,
    raridade: "lendária",
  },
  {
    title: "É o Bonnes, Vida",
    price: "0.01 ETH",
    img: bonafe,
    raridade: "lendária",
  },
  {
    title: "Miela",
    price: "0.5 ETH",
    img: miele,
    raridade: "lendária",
  },
  {
    title: "FAZ O L",
    price: "0.06 ETH",
    img: boeckL,
    raridade: "lendária",
  },
  {
    title: "Descanse em Paz",
    price: "0.08 ETH",
    img: gustavo,
    raridade: "lendária",
  },
  {
    title: "João do Mel",
    price: "0.1 ETH",
    img: joao,
    raridade: "lendária",
  },
  {
    title: "Pepe Coringado",
    price: "0.01 ETH",
    img: pepeCoringa,
    raridade: "lendária",
  },
  {
    title: "KhezaCoringa",
    price: "0.01 ETH",
    img: khezacCoringa,
    raridade: "lendária",
  },
  {
    title: "Miele Coringado",
    price: "0.01 ETH",
    img: mieleCoringa,
    raridade: "lendária",
  },
  {
    title: "Zeze Coringado",
    price: "0.01 ETH",
    img: zezeCoringa,
    raridade: "lendária",
  },
  {
    title: "Boeck Coringado",
    price: "0.01 ETH",
    img: boeckCoringa,
    raridade: "lendária",
  },
  {
    title: "Miguelito Cotoco",
    price: "0.08 ETH",
    img: miguelito,
    raridade: "lendária",
  },
  {
    title: "Zeze?????",
    price: "??? ETH",
    img: zeze,
    raridade: "lendária",
  },
  {
    title: "Eta aula boa",
    price: "0.03 ETH",
    img: kaiky,
    raridade: "lendária",
  },
  {
    title: "Cesa",
    price: "0.01 ETH",
    img: cesar,
    raridade: "lendária",
  },
  {
    title: "Yuyuka",
    price: "0.01 ETH",
    img: yuyu,
    raridade: "lendária",
  },
  {
    title: "Victor",
    price: "0.01 ETH",
    img: victor,
    raridade: "lendária",
  },
  {
    title: "Amém",
    price: "0.05 ETH",
    img: mieleAmem,
    raridade: "lendária",
  },
  {
    title: "00:00",
    price: "0.09 ETH",
    img: pepeLatao,
    raridade: "lendária",
  },
  {
    title: "EMPREGADOS DO ANO",
    price: "????????? ETH",
    img: turma,
    raridade: "lendária",
  },
];
